### PR TITLE
Specify the compatible mio version in the dependency list

### PR DESCRIPTION
**Pull request by tadzik**
With this and #63 the project builds correctly.

### CODE REVIEW

**Comment by tfreedman** [comment]
I just tried to build this, and still can't get it to build.

error[E0412]: type name `c_ares::AresError` is undefined or not in scope
  --> src/dns.rs:22:67
   |
22 | pub fn resolve_dns(domain: &str) -> Result<Option<(String, u16)>, c_ares::AresError> {
   |                                                                   ^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AresError` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `c_ares::AresError` is undefined or not in scope
  --> src/dns.rs:26:57
   |
26 |     let result: Arc<Mutex<Result<Option<(String, u16)>, c_ares::AresError>>> = Arc::new(Mutex::new(Ok(None)));
   |                                                         ^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AresError` found in your project; maybe you misspelled the name or forgot to import an external crate?

error: attempted to take value of method `scheme` on type `hyper::Url`
   --> src/matrix/client.rs:143:21
    |
143 |         if !baseurl.scheme.starts_with("https") {
    |                     ^^^^^^
    |
    = help: maybe a `()` to call it is missing? If not, try an anonymous function

error: no method named `serialize` found for type `url::host::Host<&str>` in the current scope
   --> src/matrix/client.rs:187:59
    |
187 |                 let domain = self.baseurl.host().unwrap().serialize();
    |                                                           ^^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
   --> src/matrix/client.rs:195:13
    |
195 |         ret.path_mut().unwrap().append(&mut vec!["client".to_string()]);
    |             ^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
   --> src/matrix/client.rs:196:13
    |
196 |         ret.path_mut().unwrap().append(&mut match version {
    |             ^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
   --> src/matrix/client.rs:204:13
    |
204 |         ret.path_mut().unwrap().push(endpoint.to_string());
    |             ^^^^^^^^

error: no method named `set_query_from_pairs` found for type `hyper::Url` in the current scope
   --> src/matrix/client.rs:213:13
    |
213 |         ret.set_query_from_pairs(args_with_auth);
    |             ^^^^^^^^^^^^^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
  --> src/main.rs:90:15
   |
90 |     if &*(url.path_mut().unwrap().iter().last().unwrap()) == "" {
   |               ^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
  --> src/main.rs:91:23
   |
91 |         let idx = url.path_mut().unwrap().len();
   |                       ^^^^^^^^

error: no method named `path_mut` found for type `hyper::Url` in the current scope
  --> src/main.rs:92:13
   |
92 |         url.path_mut().unwrap().remove(idx-1);
   |             ^^^^^^^^

error: aborting due to 9 previous errors

error: Could not compile `pto`.

**Comment by hackervera** [comment]
Could not compile with https://github.com/tdfischer/pto/pull/63 and this patch

**Comment by ara4n** [comment]
given pto dev seems to have died, i suggest checking out matrix-org/matrix-ircd

**Comment by ara4n** [comment]
i think pto is basically dead at this point unfortunately. suggest trying matrix-org/matrix-ircd instead.

**Pull request closed without merging**
